package intelitrader.enums;

public enum Status {
	
	
	VENDA_CONFIRMADA_PAGAMENTO_OK(100),VENDA_CONFIRMADA_PAGAMENTO_PENDENTE(102),
	VENDA_CANCELADA(135),VENDA_NAO_FINALIZADA(190),ERRO_NAO_IDENTIFICADO(999);

	Status(int i) {
		
	}

}
